spring:
  profiles:
    active:
    - smart
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yy-MM-dd HH:mm:ss
      
hr:
  raise:
    smart:
      defaultPercent: 0
      percents:
        month120:
          limit: 120
          percent: 18
        month96:
          limit: 96
          percent: 13
        month60:
          limit: 60
          percent: 7
        month30:
          limit: 30
          percent: 3
    def:
      percent: 5