spring:
  profiles:
    active: "smart"
hr:
  raise:
    smart:
      defaultPercent: 0
      percents:
        month120:
          limit: 120
          percent: 15
        month96:
          limit: 96
          percent: 10
        month60:
          limit: 60
          percent: 5
        month30:
          limit: 30
          percent: 2
    def:
      percent: 5